### PR TITLE
source-kinesis: remove local schema inference, use x-infer-schema: true

### PR DESCRIPTION
**Pull request by mdibaiee**
**Description:**

- source-kinesis: remove local schema inference, use `x-infer-schema: true` instead
- Added `sequence_number` and `partition_key` to form a key for each record received from Kinesis, this is based on the docs: "SequenceNumber is the unique identifier of the record within its shard." and "PartitionKey identifies which shard in the stream the data record is assigned to.", which I take to mean a combination of two forms a unique identifier of each record.

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/connectors/510)

### CODE REVIEW

**Comment by williamhbaker** [comment]
Does have something like stream name + message offset that could be used for the key? I think we'd need a key since I don't believe schema inference figures out keys.

**Comment by mdibaiee** [comment]
Tested this using some dummy data with AWS Kinesis Data Generator and it seemed to be working fine.

**Review by williamhbaker — APPROVED** [review]
LGTM - the only thing giving me a slight pause is including the stream name in the key and the data record itself that I had mentioned earlier. Ultimately I think that would be redundant though, since each stream will get its own binding and collection. The combination of sequence number and partition key don't sound like they would be unique _across_ streams, but that's the same as how a primary key in a database table is only unique within that table and is certainly not unique across tables.

**Comment by mdibaiee** [comment]
@williamhbaker I had the same thought regarding stream name, since we are already separating records by stream into separate collections, the keys between streams shouldn't collide, so I don't think we need to include the stream name in the document itself

**Pull request merged**
