### PR TITLE
sqlcapture: delete reduction for _meta/op: "d"

### PR DESCRIPTION
**Pull request by mdibaiee**
**Description:**

- Update the schema of `sqlcapture` connector so that when `_meta/op: "d"`, our JSONSchema specifies `reduce: { delete: true }`
- Tested this using `flowctl preview --delay 5s` and adding a log at https://github.com/estuary/flow/blob/74b61c820ffe19472eb435ad67f32b51968e26f5/crates/doc/src/reduce/strategy.rs#L357 to check whether the runtime would detect `delete: true` and it works as expected.

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/connectors/1371)

### CODE REVIEW

**Comment by willdonnelly** [comment]
The actual code change LGTM, although I'm pretty amazed that the whole `if/then/else` thing inside the schema actually works as desired.

**Comment by mdibaiee** [comment]
@willdonnelly I also didn't know about them, but this is kind of the de facto way to do it: https://github.com/estuary/flow/blob/74b61c820ffe19472eb435ad67f32b51968e26f5/crates/doc/src/reduce/strategy.rs#L1061

**Review by willdonnelly — APPROVED** [review]
Sorry, just realized I said "LGTM" in a comment but did not Officially Approve the PR.

**Review by jgraettinger — APPROVED** [review]
LGTM

Glad this worked so seamlessly -- I'd hoped it would.

**Pull request merged**
