### PR TITLE
Adding default value to credentials_title hubspot-native settings

### PR DESCRIPTION
**Pull request by Luishfs**
**Description:**

(Describe the high level scope of new or changed features)

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/connectors/1487)

### CODE REVIEW

**Review by jgraettinger — APPROVED** [review]
LGTM

**Review by jgraettinger — CHANGES_REQUESTED** [review]
Looks like this broke a lot of tests? change itself seems reasonable.

**Comment by Luishfs** [comment]
@jgraettinger Sorry, which tests are broken?

**Comment by jgraettinger** [comment]
Is this a serious question? The `estuary_cdk` is used in a bunch of connectors. See the CI run output that's part of this PR.

Some of them may have been previously broken, but we need to fix those too, because I can't tell what's a regression from this PR and what's not.

**Review by jonwihl — APPROVED** [review]
LGTM- Linkedin tests are failing because of rate limiting

**Pull request merged**
