### PR TITLE
source-mongodb: revert changes related to document decoding

### PR DESCRIPTION
**Pull request by mdibaiee**
**Description:**

- reverting the decoding changes from #985 

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/connectors/1000)

### CODE REVIEW

**Comment by williamhbaker** [comment]
Mind adding a description of how this was tested? From what I can gather, the previous encoding is suspected of producing incorrect results...nested arrays within an additional array structure I think? It is not immediately obvious to me that this change addresses that, but a test case would be pretty convincing.

**Review by jgraettinger — APPROVED** [review]
LGTM - this is removing an optimization where we attempt to avoid re-decoding the top level document?

**Comment by mdibaiee** [comment]
@jgraettinger @williamhbaker  yes, reverting back an optimization to avoid re-decoding top level document: the issue is that `RawValue`'s structure of decoding an object / array are different from what an original `cursor.Decode` yields. It works the same for scalar values, but not for objects and arrays apparently. The reasoning from what I gather is that it wants to ensure that it can encode those value back to exactly what they were in BSON format, so in an attempt to not be _lossy_, the decoding is more verbose.

**Comment by jgraettinger** [comment]
As a follow-up, then, please add integration test coverage that exercises these data types.

**Pull request merged**
